### ISSUE TITLE
Getting critical error on MetadataAPI and WoodmanCastingX

### ISSUE THREAD

**Issue by MrDemous** [PAhelper/PhoenixAdult.bundle#1290]
**Describe the bug**
When I try to match any video from MetadataAPI or WoodmanCastingX PA doesn't pull any info for the scene and I see this error in the logs.

On Metadata API

```
2021-05-19 00:38:07,305 (4024) :  INFO (logkit:16) - ******UPDATE CALLED*******
2021-05-19 00:38:07,305 (4024) :  INFO (logkit:16) - SiteNum: 3
2021-05-19 00:38:07,305 (4024) :  INFO (logkit:16) - Provider: networkMetadataAPI
2021-05-19 00:38:07,308 (4024) :  INFO (logkit:16) - Requesting GET "https://api.metadataapi.net/scenes/991924"
2021-05-19 00:38:08,170 (4024) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://991924|3?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 138, in update
    provider.update(metadata, lang, siteNum, movieGenres, movieActors)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkMetadataAPI.py", line 71, in update
    url = PAsearchSites.getSearchSearchURL(siteNum) + '/sites/%d' % network_id
TypeError: %d format: a number is required, not NoneType
```
On WoodmanCastingX

```
2021-05-19 00:21:51,934 (3d70) :  INFO (logkit:16) - ******UPDATE CALLED*******
2021-05-19 00:21:51,934 (3d70) :  INFO (logkit:16) - SiteNum: 994
2021-05-19 00:21:51,934 (3d70) :  INFO (logkit:16) - Provider: siteWoodmanCastingX
2021-05-19 00:21:51,937 (3d70) :  INFO (logkit:16) - Requesting GET "https://www.wakeupnfuck.com/scene/stella-cardo-wunf-287_22063"
2021-05-19 00:21:52,259 (3d70) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://2Qhhdda6Qnbf8RCfUQRsdp5ztgKtp67uCQNAh74q8qzKhrNt4BPgFMZWNKy5WqwuYMXGLPaGJUEaaYa7gMcW|994?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 138, in update
    provider.update(metadata, lang, siteNum, movieGenres, movieActors)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteWoodmanCastingX.py", line 31, in update
    metadata.title = detailsPageElements.xpath('//h1')[0].text_content().strip()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by DirtyRacer1337** [comment]
Fixed theporndb ccbafe015569189d1c0a415ea5343272df606c63

**Comment by MrDemous** [comment]
This fixed ThePornDB but still getting the same error on WoodmanCastingX

**Comment by DirtyRacer1337** [comment]
They have stupid protection, I know how to bypass it, but in you log request goes to `https://www.wakeupnfuck.com/scene/stella-cardo-wunf-287_22063`, that's not WoodmanCastingX

Can you send new log from search?

**Comment by MrDemous** [comment]
WakeUpnFuck is one of WoodmanCastingX sites I guess that's why it redirects to this URL which is the scene I'm trying to match anyway.

Here is the log

> 2021-05-19 16:52:24,236 (38f0) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '58140', 'name': 'WoodmanCastingX Stella Cardo'}
2021-05-19 16:52:24,237 (38f0) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/58140/tree'
2021-05-19 16:52:24,247 (38f0) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** WoodmanCastingX Stella Cardo
2021-05-19 16:52:24,247 (38f0) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: WoodmanCastingX Stella Cardo
2021-05-19 16:52:24,256 (38f0) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: WoodmanCastingX Stella Cardo
2021-05-19 16:52:24,260 (38f0) :  INFO (logkit:16) - ^^^^^^^ siteNum: 994
2021-05-19 16:52:24,260 (38f0) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-05-19 16:52:24,262 (38f0) :  INFO (logkit:16) - Search Title (before date processing): Stella Cardo
2021-05-19 16:52:24,262 (38f0) :  INFO (logkit:16) - {'siteName': 'woodmancastingx', 'searchDate': None, 'siteNum': 994, 'searchTitle': 'Stella Cardo'}
2021-05-19 16:52:24,263 (38f0) :  INFO (logkit:16) - SearchData.title: Stella Cardo
2021-05-19 16:52:24,263 (38f0) :  INFO (logkit:16) - Provider: siteWoodmanCastingX
2021-05-19 16:52:24,263 (38f0) :  INFO (logkit:16) - Requesting GET "https://www.woodmancastingx.com/search?query=Stella%20Cardo"
2021-05-19 16:52:24,826 (38f0) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-05-19 16:52:24,826 (38f0) :  DEBUG (runtime:924) - Response: [200] str, 2224 bytes
2021-05-19 16:52:31,594 (501c) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1ODE0MHM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxMzAKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovLzJRaGhkZGE2UW5iZjhSQ2ZVUVJzZHA1enRnS3RwNjd1Q1FOQWg3NHE4cXpLaHJOdDRCUGdGTVpXTkt5NVdxd3VZTVhHTFBhR0pVRWFhWWE3Z01jV3w5OTQ%40bGFuZz1lbnM0Cmd1aWRzODgKMlFoaGRkYTZRbmJmOFJDZlVRUnNkcDV6dGdLdHA2N3VDUU5BaDc0cThxektock50NEJQZ0ZNWldOS3k1V3F3dVlNWEdMUGFHSlVFYWFZYTdnTWNXfDk5NHMyCmlkcjAK
2021-05-19 16:52:31,595 (501c) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-05-19 16:52:31,595 (501c) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1ODE0MHM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxMzAKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovLzJRaGhkZGE2UW5iZjhSQ2ZVUVJzZHA1enRnS3RwNjd1Q1FOQWg3NHE4cXpLaHJOdDRCUGdGTVpXTkt5NVdxd3VZTVhHTFBhR0pVRWFhWWE3Z01jV3w5OTQ@bGFuZz1lbnM0Cmd1aWRzODgKMlFoaGRkYTZRbmJmOFJDZlVRUnNkcDV6dGdLdHA2N3VDUU5BaDc0cThxektock50NEJQZ0ZNWldOS3k1V3F3dVlNWEdMUGFHSlVFYWFZYTdnTWNXfDk5NHMyCmlkcjAK
2021-05-19 16:52:31,595 (501c) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://2Qhhdda6Qnbf8RCfUQRsdp5ztgKtp67uCQNAh74q8qzKhrNt4BPgFMZWNKy5WqwuYMXGLPaGJUEaaYa7gMcW|994?lang=en
2021-05-19 16:52:31,596 (501c) :  DEBUG (model:234) - Deserializing from C:\Users\demou\AppData\Local\Plex Media Server\Metadata\Movies\f\3cc51d2e0f3edca18e3c35872d0c5a256e8b208.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2021-05-19 16:52:31,598 (501c) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/58140/tree'
2021-05-19 16:52:31,609 (501c) :  INFO (logkit:16) - ******UPDATE CALLED*******
2021-05-19 16:52:31,609 (501c) :  INFO (logkit:16) - SiteNum: 994
2021-05-19 16:52:31,611 (501c) :  INFO (logkit:16) - Provider: siteWoodmanCastingX
2021-05-19 16:52:31,612 (501c) :  INFO (logkit:16) - Requesting GET "https://www.wakeupnfuck.com/scene/stella-cardo-wunf-287_22063"
2021-05-19 16:52:31,953 (501c) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://2Qhhdda6Qnbf8RCfUQRsdp5ztgKtp67uCQNAh74q8qzKhrNt4BPgFMZWNKy5WqwuYMXGLPaGJUEaaYa7gMcW|994?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 138, in update
    provider.update(metadata, lang, siteNum, movieGenres, movieActors)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteWoodmanCastingX.py", line 31, in update
    metadata.title = detailsPageElements.xpath('//h1')[0].text_content().strip()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2021-05-19 16:52:31,954 (501c) :  DEBUG (model:229) - Serializing to C:\Users\demou\AppData\Local\Plex Media Server\Metadata\Movies\f\3cc51d2e0f3edca18e3c35872d0c5a256e8b208.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2021-05-19 16:52:31,957 (501c) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-05-19 16:52:31,957 (501c) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes

**Comment by DirtyRacer1337** [comment]
Nah, you should use `WakeUpNFuck` for that

**Comment by MrDemous** [comment]
Okay, thanks @DirtyRacer1337 

BTW, ValeNappi now redirects to her Onlyfans page, I guess you should remove it from the supported list.
