### ISSUE TITLE
Pre folder name strip option

### ISSUE THREAD

**Issue by jababda** [PAhelper/PhoenixAdult.bundle#1299]
Would it be possible to add character striping on a folder name so that "Missa ~ clips4sale - 51941\blah" would search "clips4sale - 51941\blah"?

Right now clips4sale in particular is a pain to organize on the folder level as each folder has to start with clips4sale.

**Comment by DirtyRacer1337** [comment]
Added in 669385133fc603b44294cf77073909a685df2f3a, but it's reversed, it will strip everything after strip symbol, not before

**Comment by jababda** [comment]
Yep, I've looked at it. Is it reasonably possible to add an option for the reverse?
Directory sorting becomes basically impossible with the current functionality.

**Comment by DirtyRacer1337** [comment]
Maybe adding symbol for reversed striping will work

**Comment by jababda** [comment]
Looks like it work :). 
Form the logs at least it looks like its stripping content before the character I set(~), but I can't be sure as clips4sale is erroring now.
"\Missa ~ clips4sale - 51941\Desperate Maid Gets Blackmailed.mp4" 
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6590069/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Added support your scheme, should be working, 7e95fa6871804da73418fcd2acb0d5bb18079740, but I'll think I can revert it if other people would have problems with it and I'm not able to fix it

**Comment by jababda** [comment]
No results returning now :(
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6606883/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try with latest, should be fixed

**Comment by jababda** [comment]
Sorry for the late reply, still having an issue. Still not getting any results :(
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6710673/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try on latest

**Comment by jababda** [comment]
Works brilliant :)
