### ISSUE TITLE
Letsdoit broken

### ISSUE THREAD

**Issue by Spanishu** [PAhelper/PhoenixAdult.bundle#247]
Hi 
I have tried today to match some Herlimit and Thewhiteboxxx and none of them were found. Also looks like the webpage has been remodeled.

**Comment by kamuk90** [comment]
replace 7 line in sitePorndoePremium.py 
```
    for searchResult in searchResults.xpath('//div[@class="col col-33 t-col-50 m-col-100"]'):
```
and try. sorry can't test

**Comment by Spanishu** [comment]
That fixed it. Can we get this back into the stream @PAhelper @claygoldfinch ?

**Comment by kamuk90** [comment]
already included in #246

**Comment by claygoldfinch** [comment]
I'm actually going to reopen this. I've merged in @kamuk90's search bugfix with PR #288 (as his PR still seemed like it was a WIP). However, I'm still having issues with pulling artwork. Will investigate further.

```
2019-07-16 17:00:43,982 (10b8) :  INFO (logkit:16) - *******MEDIA TITLE****** The White Boxxx - Holly
2019-07-16 17:00:43,983 (10b8) :  INFO (logkit:16) - Getting Search Settings for: The White Boxxx - Holly
2019-07-16 17:00:43,983 (10b8) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation: The White Boxxx Holly
2019-07-16 17:00:43,992 (10b8) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: The White Boxxx Holly
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - ^^^^^^^ siteID: 217
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - the white boxxx vs the white boxxx
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - 1
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - 6
2019-07-16 17:00:43,994 (10b8) :  INFO (logkit:16) - searchTitle (before date processing): Holly
2019-07-16 17:00:43,996 (10b8) :  INFO (logkit:16) - Search Title: Holly
2019-07-16 17:00:43,996 (10b8) :  INFO (logkit:16) - Holly
2019-07-16 17:00:43,999 (10b8) :  DEBUG (networking:166) - Requesting 'https://letsdoeit.com/search.en.html?q=Holly'
2019-07-16 17:00:44,776 (10b8) :  DEBUG (runtime:88) - Sending packed state data (10924 bytes)
2019-07-16 17:00:44,776 (10b8) :  DEBUG (runtime:924) - Response: [200] str, 1444 bytes
2019-07-16 17:00:47,415 (3278) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo0OTY3NnM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxNTYKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovL2h0dHBzOl9fbGV0c2RvZWl0LmNvbV90cmFpbGVyXzc0NzZfZ2VybWFuLWFzc2lzdGFudC1zdWNrcy1hbmQtZnVja3MtbG9sbGlwb3Atc2FsZXNtYW4tYmlnLWdlb3JnZS1hdC10aGUtb2ZmaWNlfDIxNz9sYW5nPWVuczQKZ3VpZHMxMTQKaHR0cHM6X19sZXRzZG9laXQuY29tX3RyYWlsZXJfNzQ3Nl9nZXJtYW4tYXNzaXN0YW50LXN1Y2tzLWFuZC1mdWNrcy1sb2xsaXBvcC1zYWxlc21hbi1iaWctZ2VvcmdlLWF0LXRoZS1vZmZpY2V8MjE3czIKaWRyMAo_
2019-07-16 17:00:47,417 (3278) :  DEBUG (runtime:49) - Received packed state data (14160 bytes)
2019-07-16 17:00:47,420 (3278) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo0OTY3NnM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxNTYKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovL2h0dHBzOl9fbGV0c2RvZWl0LmNvbV90cmFpbGVyXzc0NzZfZ2VybWFuLWFzc2lzdGFudC1zdWNrcy1hbmQtZnVja3MtbG9sbGlwb3Atc2FsZXNtYW4tYmlnLWdlb3JnZS1hdC10aGUtb2ZmaWNlfDIxNz9sYW5nPWVuczQKZ3VpZHMxMTQKaHR0cHM6X19sZXRzZG9laXQuY29tX3RyYWlsZXJfNzQ3Nl9nZXJtYW4tYXNzaXN0YW50LXN1Y2tzLWFuZC1mdWNrcy1sb2xsaXBvcC1zYWxlc21hbi1iaWctZ2VvcmdlLWF0LXRoZS1vZmZpY2V8MjE3czIKaWRyMAo_
2019-07-16 17:00:47,421 (3278) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://https:__letsdoeit.com_trailer_7476_german-assistant-sucks-and-fucks-lollipop-salesman-big-george-at-the-office|217?lang=en
2019-07-16 17:00:47,424 (3278) :  ERROR (model:205) - Cannot read model from C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\e426d5461471f312c6fac79523b8ca44ac7fb8f.bundle\Contents\com.plexapp.agents.phoenixadult
2019-07-16 17:00:47,426 (3278) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/49676/tree'
2019-07-16 17:00:47,436 (3278) :  INFO (logkit:16) - ******UPDATE CALLED*******
2019-07-16 17:00:47,436 (3278) :  INFO (logkit:16) - 217
2019-07-16 17:00:47,437 (3278) :  INFO (logkit:16) - ******UPDATE CALLED*******
2019-07-16 17:00:47,440 (3278) :  DEBUG (networking:166) - Requesting 'https://letsdoeit.com/trailer/7476/german-assistant-sucks-and-fucks-lollipop-salesman-big-george-at-the-office'
2019-07-16 17:00:48,865 (3278) :  DEBUG (networking:166) - Requesting 'https://letsdoeit.com/pornstars-profile/holly-banks'
2019-07-16 17:00:50,174 (3278) :  DEBUG (networking:166) - Requesting 'https://letsdoeit.com/pornstars-profile/big-george'
2019-07-16 17:00:51,359 (3278) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://https:__letsdoeit.com_trailer_7476_german-assistant-sucks-and-fucks-lollipop-salesman-big-george-at-the-office|217?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4b7ace214\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 1093, in update
    metadata = PAsearchSites.sitePorndoePremium.update(metadata,siteID,movieGenres,movieActors)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\sitePorndoePremium.py", line 66, in update
    background = detailsPageElements.xpath('//picture[@class="poster"]/img')[0].get("src").replace("/1472x828/","/1920x1080/")
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4b7ace214\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2019-07-16 17:00:51,362 (3278) :  DEBUG (model:229) - Serializing to C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\e426d5461471f312c6fac79523b8ca44ac7fb8f.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2019-07-16 17:00:51,368 (3278) :  DEBUG (runtime:88) - Sending packed state data (14192 bytes)
2019-07-16 17:00:51,368 (3278) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by kamuk90** [comment]
fixed in  #296

**Comment by b0nensfw** [comment]
@pedrolara-boop 
Clearly you are not following the name scheme you shoud use : AGirlKnow - 2019-08-23 - Lana Roy Alya Stark

@claygoldfinch Could you confirm the bug is still present, the whitebox seem to be working for me

**Comment by b0nensfw** [comment]
@claygoldfinch  I just saw that it was about the poster and background part !

**Comment by pedrolara-boop** [comment]
> @pedrolara-boop
> Clearly you are not following the name scheme you shoud use : AGirlKnow - 2019-08-23 - Lana Roy Alya Stark

I think you mean "AGirlKnows - 2019-08-23 - Lana Roy Alya Stark"

It's working, however, it seems that letdoeit returns a lot of wrong results before the right one.
Had to do it manually.

Thanks for the fix guys is working!! 👍

**Comment by b0nensfw** [comment]
> @claygoldfinch I just saw that it was about the poster and background part ! If you can merge #410 I will be able to do another pull request to fix the issue

@pedrolara-boop Yes indeed for the cover, I did code a fix but I need to wait before asking for a merge and pushing the change

**Comment by Spanishu** [comment]
It seems to be broken again: 

`2019-11-19 17:11:49,888 (-4fa01ba0) :  INFO (__init__:46) - *******MEDIA TITLE****** Thewhiteboxxx 19 11 10 Lana Roy
2019-11-19 17:11:49,888 (-4fa01ba0) :  INFO (__init__:53) - Getting Search Settings for: Thewhiteboxxx 19 11 10 Lana Roy
2019-11-19 17:11:49,889 (-4fa01ba0) :  INFO (PAsearchSites:933) - mediaTitle w/ possible abbrieviation: Thewhiteboxxx 19 11 10 Lana Roy
2019-11-19 17:11:49,912 (-4fa01ba0) :  INFO (PAsearchSites:1121) - mediaTitle w/ possible abbrieviation fixed: Thewhiteboxxx 19 11 10 Lana Roy
2019-11-19 17:11:49,915 (-4fa01ba0) :  INFO (PAsearchSites:1136) - ^^^^^^^ siteID: 217
2019-11-19 17:11:49,915 (-4fa01ba0) :  INFO (PAsearchSites:1138) - ^^^^^^^ Shortening Title
2019-11-19 17:11:49,916 (-4fa01ba0) :  INFO (PAsearchSites:1139) - thewhiteboxxx 1 vs the white boxxx
2019-11-19 17:11:49,916 (-4fa01ba0) :  INFO (PAsearchSites:1198) - 3
2019-11-19 17:11:49,917 (-4fa01ba0) :  INFO (PAsearchSites:1198) - 7
2019-11-19 17:11:49,917 (-4fa01ba0) :  INFO (PAsearchSites:1198) - searchTitle (before date processing): 19 11 10 Lana Roy
2019-11-19 17:11:49,918 (-4fa01ba0) :  INFO (__init__:63) - Search Title: Lana Roy
2019-11-19 17:11:49,918 (-4fa01ba0) :  INFO (__init__:67) - Search Date: 2019-11-10
2019-11-19 17:11:49,918 (-4fa01ba0) :  INFO (__init__:72) - Lana%20Roy
2019-11-19 17:11:49,923 (-4fa01ba0) :  DEBUG (networking:166) - Requesting 'https://letsdoeit.com/search.en.html?q=Lana%20Roy'
2019-11-19 17:11:51,069 (-4fa01ba0) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'openSu$
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-36236cc4c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/home/pi/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 385, in search
    results = PAsearchSites.sitePorndoePremium.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/home/pi/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePorndoePremium.py", line 9, in search
    titleNoFormatting = searchResult.xpath('.//a[@class="main-url"]')[0].get('title')
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-36236cc4c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2019-11-19 17:11:51,074 (-4fa01ba0) :  DEBUG (runtime:88) - Sending packed state data (1188 bytes)
2019-11-19 17:11:51,075 (-4fa01ba0) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
`

**Comment by claygoldfinch** [comment]
Closing, #483 is more up to date.
