### ISSUE TITLE
Neighbor Affair (NaughtyAmerica) not matching after latest changes

### ISSUE THREAD

**Issue by PAHelper2** [PAhelper/PhoenixAdult.bundle#40]
I have a file named like so:

Neighbor Affair - 2018-12-23 - Mandy Muse.mp4

I've tried every permutation I can think of, but no luck.  Did the the recent changes break this somehow?

**Comment by PAHelper2** [comment]
Here's my log.  Looks like a bad request, 400 error:

```
2019-01-03 13:13:10,537 (7f6377fff700) :  INFO (__init__:66) - Site ID: 27
2019-01-03 13:13:10,537 (7f6377fff700) :  INFO (__init__:67) - Search Title: Mandy Muse
2019-01-03 13:13:10,538 (7f6377fff700) :  INFO (__init__:71) - Search Date: 2018-12-23
2019-01-03 13:13:10,538 (7f6377fff700) :  INFO (__init__:76) - Mandy%20Muse
2019-01-03 13:13:10,541 (7f6377fff700) :  DEBUG (networking:166) - Requesting 'https://tour.naughtyamerica.com/search?term=Mandy%20Muse Neighbor+Affair'
2019-01-03 13:13:10,825 (7f6377fff700) :  ERROR (networking:219) - Error opening URL 'https://tour.naughtyamerica.com/search?term=Mandy%20Muse Neighbor+Affair'
2019-01-03 13:13:10,826 (7f6377fff700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'openSubtitlesHash': '058d791eec29edfa', 'name': 'Neighbor Affair 2018 12 23 Mandy Muse', 'filename': '%2Fvolume1%2FVolume_1%2FPrivate%2FScene%2FNeighborAffair%2E18%2E12%2E23%2EMandy%2EMuse%2EXXX%2E1080p%2EMP4-KTR%2FNeighbor%20Affair%20-%202018-12-23%20-%20Mandy%20Muse%2Emp4', 'plexHash': 'a7c5eef576a13ab6a01c2d9d0174e5ea2839028e', 'duration': '1979567', 'id': '66679'} (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 112, in search
    results = PAsearchSites.siteNaughtyAmerica.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchAll, searchSiteID)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 7, in search
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + searchString)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 482, in ElementFromURL
    method=method,
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
    response = meth(req, response)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
    'http', request, response, code, msg, hdrs)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
    return self._call_chain(*args)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request

```

**Comment by insickin** [comment]
I am getting the same errors: https://github.com/PAhelper/PhoenixAdult.bundle/issues/31

**Comment by PAhelper** [comment]
How about now? I changed it from a space ( ) to a plus (+)...

Also worth noting, the URL it's complaining about in the log posted above is perfectly valid and works in my browser if I copy/paste. 

If this doesn't work, I may just scrap and rebuild the search function for NaughtyAmerica altogether. As I mentioned elsewhere, I'm not even sure why it's coded the way it is...

**Comment by PAHelper2** [comment]
Your change worked in finding the match, however when I select it, and it tries to pull metadata, it gets another error:

```
2019-01-03 15:01:10,662 (7f3598631700) :  DEBUG (networking:166) - Requesting 'https://tour.naughtyamerica.com/scene/mandy-muse-swallows-her-neighbors-come-24957'
2019-01-03 15:01:12,526 (7f3598631700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://_scene_mandy-muse-swallows-her-neighbors-come-24957|5?lang=en' (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 434, in update
    metadata = PAsearchSites.siteNaughtyAmerica.update(metadata,siteID,movieGenres,movieActors)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 39, in update
    subSite = detailsPageElements.xpath('//a[@class="site-title grey-text"]')[0].text_content()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2019-01-03 15:01:12,528 (7f3598631700) :  DEBUG (model:229) - Serializing to /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/Movies/1/c03e518c172d6241384ee576ecf4d782e35c8f5.bundle/Contents/com.plexapp.agents.phoenixadult/Info.xml
```

**Comment by PAHelper2** [comment]
Weird.  Some of the metadata populates, but not the actor data.

**Comment by PAhelper** [comment]
K, that should be fixed in the latest push. Thanks for the good reporting, helps make bug squashing a lot easier.

**Comment by PAHelper2** [comment]
No problem.  Happy to be able to contribute!

Unfortunately the latest push didn't change the behavior when grabbing the metadata.  Still crashes in the same place:

```
2019-01-03 16:29:50,776 (7fa418f0c700) :  DEBUG (networking:166) - Requesting 'https://tour.naughtyamerica.com/scene/mandy-muse-swallows-her-neighbors-come-24957'
2019-01-03 16:29:51,800 (7fa418f0c700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://_scene_mandy-muse-swallows-her-neighbors-come-24957|5?lang=en' (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 434, in update
    metadata = PAsearchSites.siteNaughtyAmerica.update(metadata,siteID,movieGenres,movieActors)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 39, in update
    subSite = detailsPageElements.xpath('//a[@class="site-title grey-text"]')[0].text_content()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2019-01-03 16:29:51,803 (7fa418f0c700) :  DEBUG (model:229) - Serializing to /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/Movies/1/c03e518c172d6241384ee576ecf4d782e35c8f5.bundle/Contents/com.plexapp.agents.phoenixadult/Info.xml
```

**Comment by PAHelper2** [comment]
I guess it's failing on figuring the sub site out, not the actors.

**Comment by PAHelper2** [comment]
Changed the subSite line to:

`    subSite = detailsPageElements.xpath('//a[contains(@class,"site-title grey-text")]')[0].text_content()`

And confirms it works.  Same fix as your actors change at line 52.

**Comment by fritz276** [comment]
Hmm is this error really resolved?
2019-01-04 15:40:31,793 (805bb8400) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/18767/tree'
2019-01-04 15:40:31,799 (805bb8400) :  INFO (__init__:392) - ******UPDATE CALLED*******
2019-01-04 15:40:31,799 (805bb8400) :  INFO (__init__:395) - 5
2019-01-04 15:40:31,800 (805bb8400) :  DEBUG (networking:166) - Requesting 'https://tour.naughtyamerica.com/scene/allie-haze-fucking-in-the-outdoors-with-her-brown-eyes-18493'
2019-01-04 15:40:33,048 (805bb8400) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://_scene_allie-haze-fucking-in-the-outdoors-with-her-brown-eyes-18493|5?lang=en' (most recent call last):
  File "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 434, in update
    metadata = PAsearchSites.siteNaughtyAmerica.update(metadata,siteID,movieGenres,movieActors)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 39, in update
    subSite = detailsPageElements.xpath('//a[contains(@class,"site-title grey-text"])')[0].text_content()
  File "lxml.etree.pyx", line 1459, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:40530)
  File "xpath.pxi", line 324, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:113864)
  File "xpath.pxi", line 242, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:113063)
  File "xpath.pxi", line 228, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:112935)
XPathEvalError: Invalid expression

**Comment by PAHelper2** [comment]
I tried that exact file, and it worked for me.  See below:

```
2019-01-04 08:08:50,906 (7f4b7d760700) :  INFO (__init__:45) - *******MEDIA TITLE****** Mynaughtymassage Allie Haze
2019-01-04 08:08:50,907 (7f4b7d760700) :  INFO (__init__:52) - Getting Search Settings for: Mynaughtymassage Allie Haze
2019-01-04 08:08:50,907 (7f4b7d760700) :  INFO (PAsearchSites:420) - ^^^^^^^30
2019-01-04 08:08:50,908 (7f4b7d760700) :  INFO (PAsearchSites:422) - ^^^^^^^ Shortening Title
2019-01-04 08:08:50,908 (7f4b7d760700) :  INFO (PAsearchSites:423) - mynaughtymassage a vs my naughty massage
2019-01-04 08:08:50,908 (7f4b7d760700) :  INFO (PAsearchSites:429) - 2
2019-01-04 08:08:50,909 (7f4b7d760700) :  INFO (PAsearchSites:432) - 3
2019-01-04 08:08:50,909 (7f4b7d760700) :  INFO (PAsearchSites:439) - 6
2019-01-04 08:08:50,909 (7f4b7d760700) :  INFO (__init__:66) - Site ID: 30
2019-01-04 08:08:50,910 (7f4b7d760700) :  INFO (__init__:67) - Search Title: Allie Haze
2019-01-04 08:08:50,910 (7f4b7d760700) :  INFO (__init__:76) - Allie%20Haze
2019-01-04 08:08:50,912 (7f4b7d760700) :  DEBUG (networking:166) - Requesting 'https://tour.naughtyamerica.com/search?term=Allie%20Haze+My+Naughty+Massage'
2019-01-04 08:08:51,727 (7f4b7d760700) :  INFO (siteNaughtyAmerica:10) - Result Title: Allie Haze & Kris Slater in My Naughty Massage
2019-01-04 08:08:51,728 (7f4b7d760700) :  INFO (siteNaughtyAmerica:14) - ID: _scene_allie-haze-fucking-in-the-outdoors-with-her-brown-eyes-18493
2019-01-04 08:08:51,729 (7f4b7d760700) :  INFO (siteNaughtyAmerica:17) - CurID_scene_allie-haze-fucking-in-the-outdoors-with-her-brown-eyes-18493
2019-01-04 08:08:51,735 (7f4b7d760700) :  DEBUG (runtime:88) - Sending packed state data (1352 bytes)
2019-01-04 08:08:51,736 (7f4b7d760700) :  DEBUG (runtime:924) - Response: [200] str, 784 bytes
2019-01-04 08:08:52,100 (7f4b7d760700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo2NjY4NXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxMTEKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovL19zY2VuZV9hbGxpZS1oYXplLWZ1Y2tpbmctaW4tdGhlLW91dGRvb3JzLXdpdGgtaGVyLWJyb3duLWV5ZXMtMTg0OTN8NT9sYW5nPWVuczQKZ3VpZHM2OQpfc2NlbmVfYWxsaWUtaGF6ZS1mdWNraW5nLWluLXRoZS1vdXRkb29ycy13aXRoLWhlci1icm93bi1leWVzLTE4NDkzfDVzMgppZHIwCg__
2019-01-04 08:08:52,102 (7f4b7d760700) :  DEBUG (runtime:49) - Received packed state data (1320 bytes)
2019-01-04 08:08:52,104 (7f4b7d760700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo2NjY4NXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXMxMTEKY29tLnBsZXhhcHAuYWdlbnRzLnBob2VuaXhhZHVsdDovL19zY2VuZV9hbGxpZS1oYXplLWZ1Y2tpbmctaW4tdGhlLW91dGRvb3JzLXdpdGgtaGVyLWJyb3duLWV5ZXMtMTg0OTN8NT9sYW5nPWVuczQKZ3VpZHM2OQpfc2NlbmVfYWxsaWUtaGF6ZS1mdWNraW5nLWluLXRoZS1vdXRkb29ycy13aXRoLWhlci1icm93bi1leWVzLTE4NDkzfDVzMgppZHIwCg__
2019-01-04 08:08:52,105 (7f4b7d760700) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://_scene_allie-haze-fucking-in-the-outdoors-with-her-brown-eyes-18493|5?lang=en
2019-01-04 08:08:52,139 (7f4b7d760700) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/Movies/3/412f845dc90af28bd22cc1c74059de11a1f1a03.bundle/Contents/com.plexapp.agents.phoenixadult
2019-01-04 08:08:52,140 (7f4b7d760700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/66685/tree'
2019-01-04 08:08:52,152 (7f4b7d760700) :  INFO (__init__:392) - ******UPDATE CALLED*******
```

The only error I see is this, but I'm not sure what it is about:

```
2019-01-04 08:08:52,139 (7f4b7d760700) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/Movies/3/412f845dc90af28bd22cc1c74059de11a1f1a03.bundle/Contents/com.plexapp.agents.phoenixadult
```

In Plex, that scene shows fine for me.

**Comment by PAHelper2** [comment]
For reference, my file was named: MyNaughtyMassage - Allie Haze.mp4

That added it automatically, without me needing to fix the match.

**Comment by PAhelper** [comment]
Yeah, it looks like I had a bracket out of place in line 39 of siteNaughtyAmerica.py. It'll be corrected in a new push real soon.

**Comment by fritz276** [comment]
@PAhelper - thanks, works perfect now!
