### ISSUE TITLE
Custom matching KeyError: "name='instance_token'

### ISSUE THREAD

**Issue by monkTertman** [PAhelper/PhoenixAdult.bundle#964]
**Describe the bug**
I added the PhoenixAgent in Plex and made it run through the library, It identified 1-2 videos only, then I tested with custom matching and found out this error

**Include**
1. [Scene URL](https://www.brazzers.com/video/4331471/sensual-seduction)
2. File Name: `[BrazzersExxtra] Abigail Mac  Sensual Seduction 21.01.2019`
3. Log File

While running custom match I get this error:
Logs:
```2020-08-25 02:25:08,115 (2b88) :  INFO (agentkit:961) - Searching for matches for {'year': '2019', 'id': '1523', 'name': 'brazzers - Abigail Mac Sensual Seduction 21 01 2019'}
2020-08-25 02:25:08,115 (2b88) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/1523/tree'
2020-08-25 02:25:08,121 (2b88) :  INFO (logkit:16) - *******MEDIA TITLE****** brazzers Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,122 (2b88) :  INFO (logkit:16) - Getting Search Settings for: brazzers Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,122 (2b88) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: brazzers Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,128 (2b88) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: brazzers Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - Site found with method #3
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - ^^^^^^^ siteID: 2
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - brazzers vs brazzers
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - 1
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - 8
2020-08-25 02:25:08,131 (2b88) :  INFO (logkit:16) - searchTitle (before date processing): Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,132 (2b88) :  INFO (logkit:16) - Search Title: Abigail Mac Sensual Seduction 21 01 2019
2020-08-25 02:25:08,132 (2b88) :  INFO (logkit:16) - Abigail%20Mac%20Sensual%20Seduction%2021%2001%202019
2020-08-25 02:25:08,134 (2b88) :  INFO (logkit:16) - Requesting HEAD "http://www.brazzers.com"
2020-08-25 02:25:08,335 (2b88) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '1523', 'name': 'brazzers - Abigail Mac Sensual Seduction 21 01 2019'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 858, in search
    results = PAsearchSites.siteAussieAss.search(results, encodedTitle, searchTitle, siteNum, lang, searchDate)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 16, in search
    'Instance': cookies['instance_token'],
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='instance_token', domain=None, path=None"

2020-08-25 02:25:08,335 (2b88) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-08-25 02:25:08,335 (2b88) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by PowerModder** [comment]
I just 'dummy-test' your search title. I didn't get the same error, however I got some matching issues. Replacing [BrazzersExtra] with Brazzers without [] did the matching.

**Comment by DirtyRacer1337** [comment]
Fixed in e9a4b7e8b724ed0075b00e6152b986de31636081

**Comment by monkTertman** [comment]
Hey @PowerModder , hey can you tell me how can I bulk rename my files to something what Readme recommends

**Comment by monkTertman** [comment]
Hey @DirtyRacer1337 , The issue still persists. I removed and updated the agent with new commit.

```
2020-08-25 23:44:19,869 (36f8) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjE1MjNzMgppZHM0MApicmF6emVycyAtIEFiaWdhaWwgTWFjIFNlbnN1YWwgU2VkdWN0aW9uczQKbmFtZW5zNAp5ZWFycjAK
2020-08-25 23:44:19,871 (36f8) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-08-25 23:44:19,881 (36f8) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjE1MjNzMgppZHM0MApicmF6emVycyAtIEFiaWdhaWwgTWFjIFNlbnN1YWwgU2VkdWN0aW9uczQKbmFtZW5zNAp5ZWFycjAK
2020-08-25 23:44:19,882 (36f8) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '1523', 'name': 'brazzers - Abigail Mac Sensual Seduction'}
2020-08-25 23:44:19,884 (36f8) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/1523/tree'
2020-08-25 23:44:19,891 (36f8) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json
2020-08-25 23:44:19,891 (36f8) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.agents.phoenixadult
2020-08-25 23:44:19,894 (36f8) :  INFO (logkit:16) - *******MEDIA TITLE****** brazzers Abigail Mac Sensual Seduction
2020-08-25 23:44:19,894 (36f8) :  INFO (logkit:16) - Getting Search Settings for: brazzers Abigail Mac Sensual Seduction
2020-08-25 23:44:19,894 (36f8) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: brazzers Abigail Mac Sensual Seduction
2020-08-25 23:44:19,901 (36f8) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: brazzers Abigail Mac Sensual Seduction
2020-08-25 23:44:19,903 (36f8) :  INFO (logkit:16) - Site found with method #3
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - ^^^^^^^ siteID: 2
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - brazzers vs brazzers
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - 1
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - 8
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - searchTitle (before date processing): Abigail Mac Sensual Seduction
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - Search Title: Abigail Mac Sensual Seduction
2020-08-25 23:44:19,904 (36f8) :  INFO (logkit:16) - Abigail%20Mac%20Sensual%20Seduction
2020-08-25 23:44:19,907 (36f8) :  INFO (logkit:16) - Requesting GET "http://www.brazzers.com"
2020-08-25 23:44:20,092 (36f8) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': None, 'id': '1523', 'name': 'brazzers - Abigail Mac Sensual Seduction'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 858, in search
    results = PAsearchSites.siteAussieAss.search(results, encodedTitle, searchTitle, siteNum, lang, searchDate)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 16, in search
    'Instance': cookies['instance_token'],
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='instance_token', domain=None, path=None"

2020-08-25 23:44:20,094 (36f8) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-08-25 23:44:20,095 (36f8) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```
```
2020-08-25 23:47:09,132 (1acc) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjE0NDNzMgppZHM1NApicmF6emVycyAtIEFiaWdhaWwgTWFjLCBOaWNvbGUgQW5pc3RvbiAtIEd5bSBhbmQgSnVpY2VzNApuYW1lbnM0CnllYXJyMAo_
2020-08-25 23:47:09,134 (1acc) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-08-25 23:47:09,134 (1acc) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjE0NDNzMgppZHM1NApicmF6emVycyAtIEFiaWdhaWwgTWFjLCBOaWNvbGUgQW5pc3RvbiAtIEd5bSBhbmQgSnVpY2VzNApuYW1lbnM0CnllYXJyMAo_
2020-08-25 23:47:09,134 (1acc) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '1443', 'name': 'brazzers - Abigail Mac, Nicole Aniston - Gym and Juice'}
2020-08-25 23:47:09,135 (1acc) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/1443/tree'
2020-08-25 23:47:09,142 (1acc) :  INFO (logkit:16) - *******MEDIA TITLE****** brazzers Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,144 (1acc) :  INFO (logkit:16) - Getting Search Settings for: brazzers Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,144 (1acc) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: brazzers Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,151 (1acc) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: brazzers Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,154 (1acc) :  INFO (logkit:16) - Site found with method #3
2020-08-25 23:47:09,154 (1acc) :  INFO (logkit:16) - ^^^^^^^ siteID: 2
2020-08-25 23:47:09,155 (1acc) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-08-25 23:47:09,155 (1acc) :  INFO (logkit:16) - brazzers vs brazzers
2020-08-25 23:47:09,155 (1acc) :  INFO (logkit:16) - 1
2020-08-25 23:47:09,155 (1acc) :  INFO (logkit:16) - 8
2020-08-25 23:47:09,155 (1acc) :  INFO (logkit:16) - searchTitle (before date processing): Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,157 (1acc) :  INFO (logkit:16) - Search Title: Abigail Mac Nicole Aniston Gym and Juice
2020-08-25 23:47:09,157 (1acc) :  INFO (logkit:16) - Abigail%20Mac%20Nicole%20Aniston%20Gym%20and%20Juice
2020-08-25 23:47:09,158 (1acc) :  INFO (logkit:16) - Requesting GET "http://www.brazzers.com"
2020-08-25 23:47:09,355 (1acc) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': None, 'id': '1443', 'name': 'brazzers - Abigail Mac, Nicole Aniston - Gym and Juice'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 858, in search
    results = PAsearchSites.siteAussieAss.search(results, encodedTitle, searchTitle, siteNum, lang, searchDate)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 16, in search
    'Instance': cookies['instance_token'],
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b23ab3896\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Monk\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='instance_token', domain=None, path=None"

2020-08-25 23:47:09,358 (1acc) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-08-25 23:47:09,359 (1acc) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by monkTertman** [comment]
Another log I found:

```
2020-08-26 01:59:43,638 (28ec) :  INFO (logkit:16) - *******MEDIA TITLE****** Momsincontrol Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,638 (28ec) :  INFO (logkit:16) - Getting Search Settings for: Momsincontrol Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,638 (28ec) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Momsincontrol Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,645 (28ec) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Momsincontrol Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - Site found with method #3
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - ^^^^^^^ siteID: 54
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - momsincontrol a vs moms in control
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - 3
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - 8
2020-08-26 01:59:43,648 (28ec) :  INFO (logkit:16) - searchTitle (before date processing): Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,650 (28ec) :  INFO (logkit:16) - Search Title: Ava Addams Gianna Dior Mother Daughter Boning
2020-08-26 01:59:43,650 (28ec) :  INFO (logkit:16) - Ava%20Addams%20Gianna%20Dior%20Mother%20Daughter%20Boning
2020-08-26 01:59:43,651 (28ec) :  INFO (logkit:16) - Requesting GET "http://www.brazzers.com"
2020-08-26 01:59:43,869 (200c) :  INFO (logkit:16) - Requesting GET "http://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Lucas%20Frost"
2020-08-26 01:59:43,947 (f14) :  INFO (logkit:16) - Artwork found: 8
2020-08-26 01:59:43,947 (f14) :  INFO (logkit:16) - Found https://images04-openlife.gammacdn.com/movies/74784/74784_01/previews/11/68/top_1_resized/74784_01_01.jpg in posters collection
2020-08-26 01:59:43,947 (f14) :  INFO (logkit:16) - Found https://images04-openlife.gammacdn.com/movies/74784/74784_01/previews/11/68/top_1_960x544/74784_01_01.jpg in posters collection
2020-08-26 01:59:43,948 (f14) :  INFO (logkit:16) - Found https://images03-openlife.gammacdn.com/photo_set/99940/previews/99940_1.jpg in posters collection
2020-08-26 01:59:43,950 (f14) :  INFO (logkit:16) - Requesting GET "https://images01-openlife.gammacdn.com/s/photo_set/99940/99940_001.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9pbWFnZXMwMS1vcGVubGlmZS5nYW1tYWNkbi5jb20vcy9waG90b19zZXQvOTk5NDAvOTk5NDBfMDAxLmpwZyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU5ODM5NDU4M319fV19&Signature=xh87SP5SjwAw1Jw53LXt1dxaXwaCAwxXs~UblIp0ax3KKTZndVrJDYma6XxcYctpMYJYeRMjXms4-abKmS6YZN0kh7bmrtcmLfVBjYDR~jWnhao8Z5x8~YwpvkdF0s0pWem4unmmVdy-2BWvetRMTZ9eYwnmROipdGClkZx7Wt9H04~NZvljk52-HH-prj6JIc5zoqZ1Ct4vV~lwG83YHJLI9A8WxEwVGpEEyIDExPtrJ~F3Ktv-RPcGn7uuGNeEaepJiePoC8qEOiEZkW~ryfoK6HU4qAaL3r7YiFPWZWdBPIWYTslVfSpF~IBpiuV42T28qnEYlzbPlv7u~8eNJA__&Key-Pair-Id=APKAIRQBNEZPTJQK3JAQ"
2020-08-26 01:59:44,233 (28ec) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'openSubtitlesHash': 'cad6daba0701f7bf', 'name': 'Momsincontrol Ava Addams, Gianna Dior Mother Daughter Boning', 'filename': 'X%3A%5CRECYCLER%5Cav4%5CMomsInControl%20-%20Ava%20Addams%2C%20Gianna%20Dior%20-%20Mother%20Daughter%20Boning%2Emp4', 'plexHash': '136ee008e252ed38f531e502dec2903e4a34a2fb', 'duration': '1856855', 'id': '1730'} (most recent call last):
KeyError: "name='instance_token', domain=None, path=None"

2020-08-26 01:59:44,234 (28ec) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-08-26 01:59:44,234 (28ec) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by DirtyRacer1337** [comment]
Place
```python
Log(req.text)
``` 
after 
```python
def get_Cookies(url):
    req = PAutils.HTTPRequest(sceneURL)
```
in `network1service.py` and send logs again

**Comment by monkTertman** [comment]
Hey @DirtyRacer1337 , could be related to a site blocked issue?
In my country porn sites are blocked, I used VPN and tried to do matching, and got more successful results.

**Comment by DirtyRacer1337** [comment]
Yes, I think that's a problem, I just wanted be sure

**Comment by monkTertman** [comment]
Thanks @DirtyRacer1337 
Maybe we could improve error logging to throw more user diagnose-able error.
also out of my 500 or so files only 250 got auto-matched. Will I have to match remaining one by one or is there some better way?
